name: Github Context Demo

on: [push, pull_request]

jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print Github Context
        run: |
          echo "Workflow triggered by: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Event: ${{ github.event_name }}"
          echo "Branch/Tag: ${{ github.ref_name }}"
          echo "Commit SHA: ${{ github.sha }}"

          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "PR Number: ${{ github.event.pull_request.number }}"
          fi

  job-context:
    runs-on: ubuntu-latest
    steps:
      - name: Run main task
        id: main_task
        run: exit 1 # 假设这个任务失败了
      
      - name: Notify on failure
        if: always()
        run: |
          if [ "${{ job.status }}" == "failure" ]; then
            echo "Job failed! Sending a notification."
          else
            echo "Job status is ${{ job.status }}"
          fi

  pass-data-between-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a value
        id: generator
        run: |
          echo "random_number=$(($RANDOM % 100))" >> "$GITHUB_OUTPUT"

      - name: Use the value from the previous step
        if: steps.generator.outcome == 'success'
        run: |
          echo "The random number generated was ${{ steps.generator.outputs.random_number }}"
