name: Lab-2

on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Node.js version to test'
        required: true
        type: choice
        options:
          - '18'
          - '20'
        default: '18'

jobs:
  test-matrix:
    name: Test on Node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: ${{ github.event_name == 'workflow_dispatch' && fromJSON(format('["{0}"]', github.event.inputs.node-version)) || fromJSON('["18", "20"]') }}
        include:
          - os: windows-latest
            node-version: '20'
            experimental: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: echo "Simulating installation..."

      - name: Run tests
        continue-on-error: ${{ matrix.experimental == true }}
        run: echo "Simulating tests..."

  publish-preview:
    name: Publish Preview Package
    runs-on: ubuntu-latest
    needs: test-matrix
    if: github.event_name == 'push' && github.ref_name == 'main'

    steps:
      - name: Publish to NPM
        run: |
          echo "All tests passed on all platforms!"
          echo "Publishing a preview version to NPM..."
