name: Using matrix strategy

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18, 20]

    steps:
      - name: echo "Node.js version ${{ matrix.node-version }} / OS ${{ matrix.os }}"
        run: echo "Node.js version ${{ matrix.node-version }} / OS ${{ matrix.os }}"
